extend type Account {
  id: UUID! @default(expr: "uuidV4()")
  planId: UUID!
}
extend type Plan {
  id: UUID! @default(expr: "uuidV4()")
}
extend type Tasting {
  id: UUID! @default(expr: "uuidV4()")
  accountId: UUID!
}
extend type Wine {
  id: UUID! @default(expr: "uuidV4()")
  accountId: UUID!
}
