scalar Account_Key
scalar Plan_Key
scalar Tasting_Key
scalar Wine_Key
input Account_Data {
  id: UUID
  id_expr: UUID_Expr
  planId: UUID
  planId_expr: UUID_Expr
  plan: Plan_Key
  authId: String
  authId_expr: String_Expr
  avatar: String
  avatar_expr: String_Expr
  displayName: String
  displayName_expr: String_Expr
  email: String
  email_expr: String_Expr
  firstName: String
  firstName_expr: String_Expr
  isPaid: Boolean
  lastName: String
  lastName_expr: String_Expr
  trialExpires: Timestamp
  trialExpires_expr: Timestamp_Expr
  trialExpires_time: Timestamp_Relative
}
input Account_Filter {
  _and: [Account_Filter!]
  _not: Account_Filter
  _or: [Account_Filter!]
  id: UUID_Filter
  planId: UUID_Filter
  plan: Plan_Filter
  authId: String_Filter
  avatar: String_Filter
  displayName: String_Filter
  email: String_Filter
  firstName: String_Filter
  isPaid: Boolean_Filter
  lastName: String_Filter
  trialExpires: Timestamp_Filter
  tastings_on_account: Tasting_ListFilter
  wines_on_account: Wine_ListFilter
}
input Account_ListFilter {
  count: Int_Filter
  exist: Account_Filter
}
input Account_Order {
  id: OrderDirection
  planId: OrderDirection
  authId: OrderDirection
  avatar: OrderDirection
  displayName: OrderDirection
  email: OrderDirection
  firstName: OrderDirection
  isPaid: OrderDirection
  lastName: OrderDirection
  trialExpires: OrderDirection
}
input Plan_Data {
  id: UUID
  id_expr: UUID_Expr
  description: String
  description_expr: String_Expr
  downgradablePlans: [String!]
  isActive: Boolean
  maxTasting: Int
  maxWine: Int
  name: String
  name_expr: String_Expr
  price: Float
  trialLength: Int
  upgradablePlans: [String!]
}
input Plan_Filter {
  _and: [Plan_Filter!]
  _not: Plan_Filter
  _or: [Plan_Filter!]
  id: UUID_Filter
  description: String_Filter
  downgradablePlans: String_ListFilter
  isActive: Boolean_Filter
  maxTasting: Int_Filter
  maxWine: Int_Filter
  name: String_Filter
  price: Float_Filter
  trialLength: Int_Filter
  upgradablePlans: String_ListFilter
  accounts_on_plan: Account_ListFilter
}
input Plan_ListFilter {
  count: Int_Filter
  exist: Plan_Filter
}
input Plan_Order {
  id: OrderDirection
  description: OrderDirection
  isActive: OrderDirection
  maxTasting: OrderDirection
  maxWine: OrderDirection
  name: OrderDirection
  price: OrderDirection
  trialLength: OrderDirection
}
input Tasting_Data {
  id: UUID
  id_expr: UUID_Expr
  accountId: UUID
  accountId_expr: UUID_Expr
  account: Account_Key
  acidity: Int
  alcohol: Int
  body: Int
  classification: String
  classification_expr: String_Expr
  color: String
  color_expr: String_Expr
  country: String
  country_expr: String_Expr
  date: Timestamp
  date_expr: Timestamp_Expr
  date_time: Timestamp_Relative
  description: String
  description_expr: String_Expr
  hue: String
  hue_expr: String_Expr
  intensity: String
  intensity_expr: String_Expr
  labelUri: String
  labelUri_expr: String_Expr
  price: Float
  producer: String
  producer_expr: String_Expr
  quantity: Int
  rating: Int
  region: String
  region_expr: String_Expr
  remarks: String
  remarks_expr: String_Expr
  smell: String
  smell_expr: String_Expr
  subregion: String
  subregion_expr: String_Expr
  sweet: Int
  tannin: Int
  varietal: [String!]
  vintage: String
  vintage_expr: String_Expr
}
input Tasting_Filter {
  _and: [Tasting_Filter!]
  _not: Tasting_Filter
  _or: [Tasting_Filter!]
  id: UUID_Filter
  accountId: UUID_Filter
  account: Account_Filter
  acidity: Int_Filter
  alcohol: Int_Filter
  body: Int_Filter
  classification: String_Filter
  color: String_Filter
  country: String_Filter
  date: Timestamp_Filter
  description: String_Filter
  hue: String_Filter
  intensity: String_Filter
  labelUri: String_Filter
  price: Float_Filter
  producer: String_Filter
  quantity: Int_Filter
  rating: Int_Filter
  region: String_Filter
  remarks: String_Filter
  smell: String_Filter
  subregion: String_Filter
  sweet: Int_Filter
  tannin: Int_Filter
  varietal: String_ListFilter
  vintage: String_Filter
}
input Tasting_ListFilter {
  count: Int_Filter
  exist: Tasting_Filter
}
input Tasting_Order {
  id: OrderDirection
  accountId: OrderDirection
  acidity: OrderDirection
  alcohol: OrderDirection
  body: OrderDirection
  classification: OrderDirection
  color: OrderDirection
  country: OrderDirection
  date: OrderDirection
  description: OrderDirection
  hue: OrderDirection
  intensity: OrderDirection
  labelUri: OrderDirection
  price: OrderDirection
  producer: OrderDirection
  quantity: OrderDirection
  rating: OrderDirection
  region: OrderDirection
  remarks: OrderDirection
  smell: OrderDirection
  subregion: OrderDirection
  sweet: OrderDirection
  tannin: OrderDirection
  vintage: OrderDirection
}
input Wine_Data {
  id: UUID
  id_expr: UUID_Expr
  accountId: UUID
  accountId_expr: UUID_Expr
  account: Account_Key
  classification: String
  classification_expr: String_Expr
  country: String
  country_expr: String_Expr
  date: Timestamp
  date_expr: Timestamp_Expr
  date_time: Timestamp_Relative
  description: String
  description_expr: String_Expr
  labelUri: String
  labelUri_expr: String_Expr
  price: Float
  producer: String
  producer_expr: String_Expr
  quantity: Int
  region: String
  region_expr: String_Expr
  subregion: String
  subregion_expr: String_Expr
  varietal: [String!]
  vintage: String
  vintage_expr: String_Expr
}
input Wine_Filter {
  _and: [Wine_Filter!]
  _not: Wine_Filter
  _or: [Wine_Filter!]
  id: UUID_Filter
  accountId: UUID_Filter
  account: Account_Filter
  classification: String_Filter
  country: String_Filter
  date: Timestamp_Filter
  description: String_Filter
  labelUri: String_Filter
  price: Float_Filter
  producer: String_Filter
  quantity: Int_Filter
  region: String_Filter
  subregion: String_Filter
  varietal: String_ListFilter
  vintage: String_Filter
}
input Wine_ListFilter {
  count: Int_Filter
  exist: Wine_Filter
}
input Wine_Order {
  id: OrderDirection
  accountId: OrderDirection
  classification: OrderDirection
  country: OrderDirection
  date: OrderDirection
  description: OrderDirection
  labelUri: OrderDirection
  price: OrderDirection
  producer: OrderDirection
  quantity: OrderDirection
  region: OrderDirection
  subregion: OrderDirection
  vintage: OrderDirection
}
