extend type Query {
  """
  Look up a single Account based on `id` or `key` and return selected fields (or `null` if not found).
  """
  account(id: UUID, key: Account_Key): Account
  """
  Look up a single Plan based on `id` or `key` and return selected fields (or `null` if not found).
  """
  plan(id: UUID, key: Plan_Key): Plan
  """
  Look up a single Tasting based on `id` or `key` and return selected fields (or `null` if not found).
  """
  tasting(id: UUID, key: Tasting_Key): Tasting
  """
  Look up a single Wine based on `id` or `key` and return selected fields (or `null` if not found).
  """
  wine(id: UUID, key: Wine_Key): Wine
  """
  List Account entries in the table, optionally filtered by `where` conditions.
  """
  accounts(where: Account_Filter, orderBy: [Account_Order!], limit: Int = 100): [Account!]!
  """
  List Plan entries in the table, optionally filtered by `where` conditions.
  """
  plans(where: Plan_Filter, orderBy: [Plan_Order!], limit: Int = 100): [Plan!]!
  """
  List Tasting entries in the table, optionally filtered by `where` conditions.
  """
  tastings(where: Tasting_Filter, orderBy: [Tasting_Order!], limit: Int = 100): [Tasting!]!
  """
  List Wine entries in the table, optionally filtered by `where` conditions.
  """
  wines(where: Wine_Filter, orderBy: [Wine_Order!], limit: Int = 100): [Wine!]!
}
