extend type Plan {
  """
  ✨ List User entries in a one-to-many relationship with this object (i.e. where `User.plan` equals this object).
  """
  users_on_plan(where: User_Filter, orderBy: [User_Order!], limit: Int = 100): [User!]!
}
extend type User {
  """
  ✨ List Tasting entries in a one-to-many relationship with this object (i.e. where `Tasting.user` equals this object).
  """
  tastings_on_user(where: Tasting_Filter, orderBy: [Tasting_Order!], limit: Int = 100): [Tasting!]!
  """
  ✨ List Wine entries in a one-to-many relationship with this object (i.e. where `Wine.user` equals this object).
  """
  wines_on_user(where: Wine_Filter, orderBy: [Wine_Order!], limit: Int = 100): [Wine!]!
}
