extend type Account {
  """
  ✨ List Tasting entries in a one-to-many relationship with this object (i.e. where `Tasting.account` equals this object).
  """
  tastings_on_account(where: Tasting_Filter, orderBy: [Tasting_Order!], limit: Int = 100): [Tasting!]!
  """
  ✨ List Wine entries in a one-to-many relationship with this object (i.e. where `Wine.account` equals this object).
  """
  wines_on_account(where: Wine_Filter, orderBy: [Wine_Order!], limit: Int = 100): [Wine!]!
}
extend type Plan {
  """
  ✨ List Account entries in a one-to-many relationship with this object (i.e. where `Account.plan` equals this object).
  """
  accounts_on_plan(where: Account_Filter, orderBy: [Account_Order!], limit: Int = 100): [Account!]!
}
